blank_issues_enabled: false

contact_links:
  - name: Common Issues
    url: https://pam_mmpose.readthedocs.io/en/latest/faq.html
    about: Check if your issue already has solutions
  - name: MMPose Documentation
    url: https://pam_mmpose.readthedocs.io/en/latest/
    about: Check if your question is answered in docs
